export type IconName =
    "add-user"
    | "app-logo"
    | "chevron-left"
    | "chevron-right"
    | "close"
    | "heart"
    | "home"
    | "loader"
    | "log-in"
    | "log-out"
    | "musical-note"
    | "music"
    | "pencil"
    | "search"
    | "user"
